Fix/invalid amount error
ProjectSwaptor/swaptor-monorepo pull request #22
Opened 2023-09-19 14:57 UTC by prime623

Disable Create/Accept Swap buttons when the user doesn't have a sufficient balance

2023-10-01 09:08 UTC, GitMark0 requested changes
Frontend has troubles building for some reason. Try to build it locally first and see where is the error.

2023-10-05 12:26 UTC, DonRavle commented on frontend/src/pages/components/create-swap/SwapButton.tsx
> +      if (parsedBalance.lt(parsedTokenData)) {
what if `parsedBalance` is equal to `parsedTokenData`?

2023-10-05 12:26 UTC, DonRavle commented on frontend/src/pages/components/create-swap/SwapButton.tsx
> +      if (parsedBalance.lt(parsedTokenData)) {
instead of using whole if-else statement, you can just write something like this:

`setEnoughBalance(!parsedBalance.lt(parsedTokenData))`

2023-10-05 12:26 UTC, DonRavle commented on frontend/src/pages/components/create-swap/SwapButton.tsx
> +    } else {
there is no case where this `else` statement will never be accessed. What is the logic behind it?

2023-10-05 12:26 UTC, DonRavle commented on frontend/src/pages/components/create-swap/SwapButton.tsx
> +      tokenDataParsed,
what is the reason for segregation of `tokenDataParsed`? If we leave like it was before, we can remove `handleApproveForCreateSwap` completely and use `handleApprove` everywhere instead

2023-10-05 12:26 UTC, DonRavle commented on frontend/src/pages/components/overview/OverviewButtons.tsx
> +      if (parsedBalance.lt(parsedTokenData)) {
same comments as in `SwapButton.tsx`

2023-10-06 13:50 UTC, prime623 commented on frontend/src/pages/components/create-swap/SwapButton.tsx
> +      if (parsedBalance.lt(parsedTokenData)) {
First comment: Then the user has enough balance so it should be set to true.

2023-10-06 13:50 UTC, prime623 commented on frontend/src/pages/components/create-swap/SwapButton.tsx
> +    } else {
There is a case where this will be accessed, and that is when the user has `enoughBalance` and doesn't have `enoughAllowance`.

2023-10-06 13:50 UTC, prime623 commented on frontend/src/pages/components/create-swap/SwapButton.tsx
> +      tokenDataParsed,
I reverted `tokenDataParsed` to how it was before, however I'd still like to leave this function here so the `handleSwapButtonClick` function doesn't get messy with all the cases. If you disagree let me know once you've had another look at the modified code.

2023-10-13 18:53 UTC, merged