Fix/additional allowance
ProjectSwaptor/swaptor-monorepo pull request #23
Opened 2023-09-19 14:58 UTC by prime623

Check for necessary additional allowance on Create Swap when approving tokens.

2023-10-01 09:03 UTC, GitMark0 requested changes

2023-10-01 09:03 UTC, GitMark0 commented on backend/src/swaps/swaps.service.ts
> +export const getUserActiveSwaps = async (
Test this

2023-10-01 09:03 UTC, GitMark0 commented on backend/src/swaps/swaps.service.ts
> +  tokenAddress: string,
Shouldn't this be optional? If a user wants to get all of his active swaps, regardless of the token address for example.

2023-10-01 09:03 UTC, GitMark0 commented on backend/src/swaps/swaps.service.ts
> +  return { userActiveSwaps };
Why are we returning an object here?

2023-10-01 09:03 UTC, GitMark0 commented on backend/src/swaps/swaps.controller.ts
> +  const exists = await service.getUserActiveSwaps(
This isn't really a good name for the return of `getUserActiveSwaps`.

2023-10-02 05:50 UTC, prime623 commented on backend/src/swaps/swaps.service.ts
> +  return { userActiveSwaps };
Is there a reason not to? I think it's more readable when the response is returned in this format, not just as an array of objects.

2023-10-13 19:05 UTC, merged